-- Nyx Bot V2: lista negra permanente por grupo
create table if not exists public.group_blacklist (
  id bigint generated by default as identity primary key,
  group_id text not null,
  user_jid text not null,
  by_jid text,
  reason text not null default '',
  created_at timestamptz not null default now(),
  unique (group_id, user_jid)
);

create index if not exists idx_group_blacklist_group
  on public.group_blacklist (group_id);

create index if not exists idx_group_blacklist_user
  on public.group_blacklist (user_jid);

alter table public.group_blacklist enable row level security;

-- O bot usa a SERVICE KEY no servidor. Nenhuma policy pública é necessária.
